
target 'MyLibrary_Example', :exclusive => true do
  pod 'MyLibrary', :path => '../'
end

target 'MyLibrary_Tests', :exclusive => true do
  pod 'MyLibrary', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
